# Changes here will be overwritten by Copier
_commit: 2.5.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: James.OHea@diamond.ac.uk
author_name: James O'Hea
component_lifecycle: production
component_owner: group:default/sscc
component_type: library
description:
    Python library for communicating with Delta Tau PMACs (both Turbo and
    Power)
distribution_name: dls-pmaclib
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: dls_pmaclib
pypi: true
repo_name: dls-pmac-lib
type_checker: mypy
